### ISSUE TITLE
Index view for Local Names

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria-v2#169]
- [x] I can see existing local names
- [ ] ~~I have a link to create new names (see #170)~~
- [ ] ~~I have links to edit names (see #170)~~
- [ ] ~~I have links to tombstone names (see #172)~~

**INDEX VIEW**
![adrl2 - 169 - local names - i](https://cloud.githubusercontent.com/assets/3064318/6907709/21b1cff6-d6fe-11e4-9bc0-cc4539e1f6ce.png)

**Comment by val99erie** [comment]
We should break up this story into smaller stories:

1. Index page for existing local names + navigation to get to that page
2.  New/Create and Edit/Update forms
3. Some story that covers delete vs tombstone

**Comment by mark-dce** [comment]
Done - see #170, #171, #172
The tombstone comment was basically to say don't delete, only tombstone (unless someone wants to argue strongly for permanent deletions, but I think they're actually a bad idea)

**Comment by val99erie** [comment]
@mark-dce I have a couple questions:

1. Should all users be able to view the local names, or only admin users?

2. I would like to make this page a blacklight-style catalog page.  I think users will want the ability to facet, search, sort, etc.  The way the code is currently, it looks like a catalog search results page.  Can I leave it like that, or do you want me to change the UI to match the wireframe above?

**Comment by val99erie** [comment]
@mark-dce Here is what the page currently looks like, with both local names and local subjects:

![local_auth](https://cloud.githubusercontent.com/assets/298865/8169841/d2f55e90-1371-11e5-8c5e-7fe4e2960b34.png)

**Comment by mark-dce** [comment]
@val99erie these views are for admins only - normal users would just see the data displayed in a normal item show view.  The primary use is to de-duplicate entries that are automatically created on bulk ingest (xml or csv) - say one group of records had "Mark H. Bussey", another had "Bussey, M. Hamilton" - on import, these would trigger the creation of two separate name entries, but a responsible human could later discover this and want to merge them all into a single URI and change the label to the preferred form of "Bussey, Mark H."

So for the questions above. 
1. Only admins should be able to edit local names.  From a linked-open-data perspective, there probably needs to be a read-only way to resolve the URI for the local name and get a predicate and human readable string back.
2. Your UI looks great if you can add a type indicator for each entry in the list:
* Conway, Joel - Personal Name
* Frodo Baggins - Personal Name
* EFF - Organizational Name
* Birds of California - Topic
(I'm not sure the bookmark option makes sense in this context.  If you could remove it, that would be nice, if not we can see how UCSB reacts to it)

**Comment by val99erie** [comment]
I updated #170 and #172 to include the links to the specific actions (new, edit, delete).  I removed those requirements from this story.
