### ISSUE TITLE
Collection Management

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria-v2#177]
Create a set of stories to allow collections to be managed in ADRL 
- [ ] Edit a collection's metadata
- [ ] Manage a collection's membership
- [ ] Create a new collection

**Comment by mark-dce** [comment]
Most of this functionality is addressed in other ways.  Will open specific ticket as additional unimplemented collection functionality is required
