### ISSUE TITLE
Index View for Local Subjects

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria-v2#205]
- [x] I can see existing local subjects
- [x] I have a link to create new subjects (see #206)
- [x] I have links to edit subjects (see #206)
- [x] I have links to delete names (see #204)

**INDEX VIEW - this is the wireframe for Names, Subjects should be very similar**
![adrl2 - 169 - local names - i](https://cloud.githubusercontent.com/assets/3064318/6907709/21b1cff6-d6fe-11e4-9bc0-cc4539e1f6ce.png)

**Comment by jcoyne** [comment]
Is this done by "http://localhost:3000/local_authorities" ?

**Comment by jcoyne** [comment]
Where should the URI display. That's not on this wireframe, but its of the highest importance.
