### ISSUE TITLE
Crosswalk ETD properties to RDF

### ISSUE THREAD

**Issue by jcoyne** [curationexperts/alexandria-v2#275]
We're reading these properties out of MARC, what RDF properties/predicates should they use.

- [x] isbn
- [x] published #342
- [x] description -> extent #350
- [x] advisor #301
- [x] dissertation #338
- [x] keyword #346
- [x] bibliography - removed from ADRL 2.0 #340
- [x] summary -> description #348
- [x] genre  - removed from ADRL 2.0 #340
- [x] degree_grantor #347
- [x] discipline - removed from ADRL 2.0 #340
- [x] fulltext_link #351
- [x] filename #292

Then fix https://github.com/curationexperts/alexandria-v2/blob/8201c34150a4acfbc42512cd917dcd3e91197365/lib/object_factory_writer.rb#L38-L50

**Comment by mark-dce** [comment]
attribute  |  predicate
---------: | :-------------------
isbn | http://id.loc.gov/vocabulary/identifiers/isbn

**Comment by jcoyne** [comment]
Here's what we're importing: https://github.com/curationexperts/alexandria-v2/blob/master/traject_config.rb#L39-L120

**Comment by mark-dce** [comment]
Individual attributes covered in stories as listed above.
